[tool.poetry]
name = "op-tcg"
version = "0.1.0"
description = ""
authors = ["fteutsch <florianteutsch@yahoo.de>"]
license = "MIT"
readme = "README.md"
packages = [{include = "op_tcg"}]

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.0"
pydantic = "^2.7.0"
click = "^8.1.7"
google-cloud-bigquery = "^3.20.1"
pandas = "^2.2.2"
pyarrow = "^15.0.2"


[tool.poetry.group.crawler.dependencies]
requests = "^2.31.0"
scrapy = "^2.11.1"
beautifulsoup4 = "^4.12.3"


[tool.poetry.group.frontend.dependencies]
streamlit = "^1.33.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
optcg = 'op_tcg.cli_app:app'