from .Admin_Leader_Upload import main_admin_leader_upload
from .Leader_Detail_Analysis import main_leader_detail_analysis
from .Leader_Decklists import main_leader_detail_analysis_decklists
from .Leader_Matchup import main_meta_analysis
from .Leader_Card_Movement import main_leader_card_movement
from .Leader_Tournament import main_tournaments
from .Card_Popularity import main_card_meta_analysis
from .Support_Bug_Report import main_bug_report