from .Admin_Leader_Upload import main_admin_leader_upload
from .Leader_Detail_Analysis import main_leader_detail_anylsis
from .Leader_Detail_Analysis_Decklists import main_leader_detail_analysis_decklists
from .Leader_Meta_Analysis import main_meta_analysis
from .Leader_Decklist_Movement import main_leader_decklist_movement