SUB_PAGE_LEADER_MATCHUP = "Leader Matchup"
SUB_PAGE_LEADER_DECKLIST = "Leader Decklist"
SUB_PAGE_LEADER = "Leader"
SUB_PAGE_LEADER_DECKLIST_MOVEMENT = "Leader Decklist Movement"
SUB_PAGE_LEADER_CARD_MOVEMENT = "Leader Card Movement"
SUB_PAGE_CARD_POPULARITY = "Card Popularity"

Q_PARAM_EASIEST_OPPONENT = "easiest_opponent_lid"
Q_PARAM_HARDEST_OPPONENT = "hardest_opponent_lid"
Q_PARAM_LEADER_ID = "lid"
Q_PARAM_META = "meta"
Q_PARAM_N_CARD = "n-cards"
Q_PARAM_ANCHOR_TAG = "anchor"
